version: '6.0-beta-5_r{build}'

image: Visual Studio 2017
configuration: Release
platform: Any CPU

build:
  project: HedgeModManager.sln
  verbosity: minimal
  
artifacts:
 - path: 'HedgeModManager\bin\Release'
   name: 'HedgeModManager-$(APPVEYOR_REPO_COMMIT)'
   type: zip
