version: '6.0-beta-5_r{build}'

image: Visual Studio 2017
configuration: Release
platform: Any CPU

build:
  project: HedgeModManager.sln
  verbosity: minimal
  
artifacts:
 - path: 'HedgeModManager\bin\Release'
   name: '$(appveyor_project_name) $(appveyor_build_version)'
   type: zip
